spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

# mybatis mapper.xml location 설정(기본 location: main/resources 에 추가된 부분 설정)
mybatis:
  mapper-locations: mapper/*.xml