package me.parker.springbootmybatismapping.model;

public enum GenreType {
    ACTION, COMEDY, DRAMA, HORROR, THRILLER, SF, WAR, ROMANCE,
    DOCUMENTARY, ANIMATION, FANTASY, MUSICAL, ADVENTURE, CRIME,
    WESTERN, MYSTERY, HISTORICAL, SPORT, FAMILY, MUSIC, BIOGRAPHY,
    SHORT, REALITY_TV, GAME_SHOW, TALK_SHOW, NEWS, ADULT, FILM_NOIR,
    EXPERIMENTAL, COMMERCIAL, OTHER
}
